/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomFooter: typeof import('./components/BottomFooter.vue')['default']
    GloButton: typeof import('./components/GloButton.vue')['default']
    GloImage: typeof import('./components/GloImage.vue')['default']
    ListOne: typeof import('./components/ListOne.vue')['default']
    ListOneA: typeof import('./components/ListOneA.vue')['default']
    ListOneB: typeof import('./components/ListOneB.vue')['default']
    ListOneC: typeof import('./components/ListOneC.vue')['default']
    ListOneD: typeof import('./components/ListOneD.vue')['default']
    ListTwo: typeof import('./components/ListTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTips: typeof import('./components/ScrollTips.vue')['default']
    ScrollTipsA: typeof import('./components/ScrollTipsA.vue')['default']
    SVGTextOne: typeof import('./components/SVGTextOne.vue')['default']
    TopHeader: typeof import('./components/TopHeader.vue')['default']
  }
}
